title: My Awesome Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome site where I blog about my adventures in coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: johndoe
github_username:  johndoe

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
